// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GFGFVfj_ddq-Ua2Uqs4sOs2hIvGizas',
    appId: '1:151972593003:web:05e555a6740c1c8b03202e',
    messagingSenderId: '151972593003',
    projectId: 'dam2024-576f1',
    authDomain: 'dam2024-576f1.firebaseapp.com',
    storageBucket: 'dam2024-576f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvRGE4Ebn6OR8s_NXPoRci7qv60tdtANs',
    appId: '1:151972593003:android:a48f7b68c98b67fc03202e',
    messagingSenderId: '151972593003',
    projectId: 'dam2024-576f1',
    storageBucket: 'dam2024-576f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyH9BvbML0lz3ysgVaVyWu6fdbXxy4qc',
    appId: '1:151972593003:ios:602cdc55cacd381303202e',
    messagingSenderId: '151972593003',
    projectId: 'dam2024-576f1',
    storageBucket: 'dam2024-576f1.firebasestorage.app',
    iosClientId: '151972593003-c93cmr6siq7pav1u1443pi3c4uqb36p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.certamen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPyH9BvbML0lz3ysgVaVyWu6fdbXxy4qc',
    appId: '1:151972593003:ios:602cdc55cacd381303202e',
    messagingSenderId: '151972593003',
    projectId: 'dam2024-576f1',
    storageBucket: 'dam2024-576f1.firebasestorage.app',
    iosClientId: '151972593003-c93cmr6siq7pav1u1443pi3c4uqb36p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.certamen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0GFGFVfj_ddq-Ua2Uqs4sOs2hIvGizas',
    appId: '1:151972593003:web:c14608ae8dc28d4903202e',
    messagingSenderId: '151972593003',
    projectId: 'dam2024-576f1',
    authDomain: 'dam2024-576f1.firebaseapp.com',
    storageBucket: 'dam2024-576f1.firebasestorage.app',
  );
}
